//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aaru.VideoNow {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DiscImageChef.VideoNow.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }

        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }

        public static string FileCannotBeOpened {
            get {
                return ResourceManager.GetString("FileCannotBeOpened", resourceCulture);
            }
        }

        public static string FileIsTooBig {
            get {
                return ResourceManager.GetString("FileIsTooBig", resourceCulture);
            }
        }

        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }

        public static string SearchingFirstFrame {
            get {
                return ResourceManager.GetString("SearchingFirstFrame", resourceCulture);
            }
        }

        public static string NoFrameFound {
            get {
                return ResourceManager.GetString("NoFrameFound", resourceCulture);
            }
        }

        public static string FirstFrameFoundAt {
            get {
                return ResourceManager.GetString("FirstFrameFoundAt", resourceCulture);
            }
        }

        public static string FirstFrameIsAtSectorBoundary {
            get {
                return ResourceManager.GetString("FirstFrameIsAtSectorBoundary", resourceCulture);
            }
        }

        public static string FirstFrameIsNotAtSectorBoundary {
            get {
                return ResourceManager.GetString("FirstFrameIsNotAtSectorBoundary", resourceCulture);
            }
        }

        public static string ExtractingAudio {
            get {
                return ResourceManager.GetString("ExtractingAudio", resourceCulture);
            }
        }

        public static string LookingForMoreFrames {
            get {
                return ResourceManager.GetString("LookingForMoreFrames", resourceCulture);
            }
        }

        public static string FrameAndNextAreNotAligned {
            get {
                return ResourceManager.GetString("FrameAndNextAreNotAligned", resourceCulture);
            }
        }

        public static string FrameFoundAtPosition {
            get {
                return ResourceManager.GetString("FrameFoundAtPosition", resourceCulture);
            }
        }

        public static string FrameIsAtSectorBoundary {
            get {
                return ResourceManager.GetString("FrameIsAtSectorBoundary", resourceCulture);
            }
        }

        public static string FrameIsNotAtSectorBoundary {
            get {
                return ResourceManager.GetString("FrameIsNotAtSectorBoundary", resourceCulture);
            }
        }

        public static string FramesFound {
            get {
                return ResourceManager.GetString("FramesFound", resourceCulture);
            }
        }

        public static string ExtractingVideo {
            get {
                return ResourceManager.GetString("ExtractingVideo", resourceCulture);
            }
        }
    }
}
